name: stark-qa
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - anthropic
  - bs4
  - gdown
  - huggingface_hub
  - langchain
  - langdetect
  - multiprocess
  - nltk
  - numpy
  - ogb
  - openai
  - pandas
  - PyTDC
  - tqdm
  - transformers
  - pip
  - pip:
      - neo4j
      - python-dotenv
      - torch
      - fpdf2
      - torch_geometric
      - torchmetrics
      - llama-index
      - llama-index-program-openai
      - llama-index-llms-openai
      - llama-index-embeddings-azure-openai
      - llama-index-llms-azure-openai
      - .
