name: stark-qa
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - anthropic
  - bs4
  - gdown
  - huggingface_hub
  - langchain
  - langdetect
  - multiprocess
  - nltk
  - numpy
  - ogb
  - openai
  - pandas
  - PyTDC
  - tqdm
  - transformers
  - pip
  - pip:
      - torch
      - torch_geometric
      - torchmetrics
      - .
